version: '3.8'
services:
  app:
    # 使用./DockerFile构建SpringBoot后端镜像
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:mysql://db:3306/unigpt
      - DB_USERNAME=unigpt
      - DB_PASSWORD=Kiwi339bleavescreeper
      - HTTP_PROXY_HOST=192.168.1.100
      - HTTP_PROXY_PORT=7890
      - DB_HOST=124.70.222.207
      - FRONTEND_SERVER_URL=http://124.70.222.207:3000

  db:
    image: mysql:8.2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: unigpt
      MYSQL_PASSWORD: Kiwi339bleavescreeper
      MYSQL_DATABASE: unigpt
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db-data:
