spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: file:./src/main/resources/static/
  application:
    name: unigpt
  datasource:
    url: jdbc:mysql://124.70.222.207:3306/unigpt
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
logging:
  level:
    org.springframework.web.socket: DEBUG

server:
   port: 8080
   ssl:
      key-store: keystore.p12
      key-store-password: unigpt
      keyStoreType: PKCS12
      keyAlias: tomcat

imageServerUrl: http://124.70.222.207:10339
frontendServerUrl: ${FRONTEND_SERVER_URL:http://localhost:3000}
jaccountClientId: ov3SLrO4HyZSELxcHiqS
jaccountClientSecret: B9919DDA3BD9FBF7ADB9F84F67920D8CB6528620B9586D1C