name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master  # 当主分支收到推送时触发

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        outputs: type=docker,name=unigpt-backend-app,dest=image.tar

    - name: Copy Docker Image to remote server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 124.70.222.207
        username: uni
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        source: "image.tar"
        target: ~/

    - name: Load Docker Image on remote server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 124.70.222.207
        username: uni
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: docker load -i ~/image.tar; rm ~/image.tar

        
